### ISSUE TITLE
Not an really issue

### ISSUE THREAD

**Issue by frostzzone** [cabalex/cabalex.github.io#2]
Hey @cabalex I would contact you on discord but discord doesn't allow messaging to users who you dont share a server with.

But,

I ported your xml-unpacker to work on google colab just thought you might like it.
[The upacker](https://github.com/frostzzone/xml-unpacker) it works online and I gave a guide on how to use it 😃 (I gave you credit)
[Delete/close this "issue" when your done with it]

**Comment by cabalex** [comment]
Forgot to close this- thank you for your support! Definitely can be confusing on how to install Python and the required modules for the first time, so your Colab notebook definitely helps :)
